### ISSUE TITLE
error ：nvcc fatal   : Unknown option '-generate-dependencies-with-compile' ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by Q455** [Turoad/CLRNet#111]
When i follow the [README.md](https://github.com/Turoad/CLRNet#readme), 
Try : python setup.py build develop.  
Then i got some erros , which i could not overcome for a few weeks . The main erro have  been described in the tittle of the issue.  Otherwise all these attempts are under Windows not linux .  
ALL logs has been displayed  as follows:

(clrnet) D:\Li_Yong_Hang\CLRNet-main\CLRNet-main>python setup.py build develop
running build
running build_py
running egg_info
writing clrnet.egg-info\PKG-INFO
writing dependency_links to clrnet.egg-info\dependency_links.txt
writing requirements to clrnet.egg-info\requires.txt
writing top-level names to clrnet.egg-info\top_level.txt
reading manifest file 'clrnet.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'clrnet.egg-info\SOURCES.txt'
running build_ext
C:\Users\ps\.conda\envs\clrnet\lib\site-packages\torch\utils\cpp_extension.py:311: UserWarning:

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (cl 19.00.24210) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 5.0 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 5 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
building 'clrnet.ops.nms_impl' extension
C:\Users\ps\.conda\envs\clrnet\lib\site-packages\torch\cuda\__init__.py:104: UserWarning:
NVIDIA GeForce RTX 3080 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Emitting ninja build file D:\Li_Yong_Hang\CLRNet-main\CLRNet-main\build\temp.win-amd64-3.8\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc --generate-dependencies-with-compile --dependency-output D:\Li_Yong_Hang\CLRNet-main\CLRNet-main\build\temp.win-amd64-3.8\Release\clrnet/ops/csrc\nms_kernel.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\Users\ps\.conda\envs\clrnet\lib\site-packages\torch\include -IC:\Users\ps\.conda\envs\clrnet\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\ps\.conda\envs\clrnet\lib\site-packages\torch\include\TH -IC:\Users\ps\.conda\envs\clrnet\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\ps\.conda\envs\clrnet\include -IC:\Users\ps\.conda\envs\clrnet\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c D:\Li_Yong_Hang\CLRNet-main\CLRNet-main\clrnet\ops\csrc\nms_kernel.cu -o D:\Li_Yong_Hang\CLRNet-main\CLRNet-main\build\temp.win-amd64-3.8\Release\clrnet/ops/csrc\nms_kernel.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_impl -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75
FAILED: D:/Li_Yong_Hang/CLRNet-main/CLRNet-main/build/temp.win-amd64-3.8/Release/clrnet/ops/csrc/nms_kernel.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc --generate-dependencies-with-compile --dependency-output D:\Li_Yong_Hang\CLRNet-main\CLRNet-main\build\temp.win-amd64-3.8\Release\clrnet/ops/csrc\nms_kernel.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\Users\ps\.conda\envs\clrnet\lib\site-packages\torch\include -IC:\Users\ps\.conda\envs\clrnet\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\ps\.conda\envs\clrnet\lib\site-packages\torch\include\TH -IC:\Users\ps\.conda\envs\clrnet\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\ps\.conda\envs\clrnet\include -IC:\Users\ps\.conda\envs\clrnet\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c D:\Li_Yong_Hang\CLRNet-main\CLRNet-main\clrnet\ops\csrc\nms_kernel.cu -o D:\Li_Yong_Hang\CLRNet-main\CLRNet-main\build\temp.win-amd64-3.8\Release\clrnet/ops/csrc\nms_kernel.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_impl -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\ps\.conda\envs\clrnet\lib\site-packages\torch\utils\cpp_extension.py", line 1667, in _run_ninja_build
    subprocess.run(
  File "C:\Users\ps\.conda\envs\clrnet\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 100, in <module>
    setup(name='clrnet',
  File "C:\Users\ps\.conda\envs\clrnet\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\ps\.conda\envs\clrnet\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\ps\.conda\envs\clrnet\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\ps\.conda\envs\clrnet\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\ps\.conda\envs\clrnet\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\ps\.conda\envs\clrnet\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\ps\.conda\envs\clrnet\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\ps\.conda\envs\clrnet\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\ps\.conda\envs\clrnet\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\ps\.conda\envs\clrnet\lib\site-packages\torch\utils\cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\ps\.conda\envs\clrnet\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\ps\.conda\envs\clrnet\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\ps\.conda\envs\clrnet\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\ps\.conda\envs\clrnet\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\Users\ps\.conda\envs\clrnet\lib\site-packages\torch\utils\cpp_extension.py", line 681, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\Users\ps\.conda\envs\clrnet\lib\site-packages\torch\utils\cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Users\ps\.conda\envs\clrnet\lib\site-packages\torch\utils\cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by PZysq** [comment]
I have the same problem as you but don't know how to solve it yet

**Comment by yunhaklee** [comment]
How to solve this problem?
I am using the  RTX 3090 and installed cuda11.1

**Comment by Q455** [comment]
I think you may should try the project on Linux , which has been described in the origin project.


 李勇杭
 ***@***.***
  



---- Replied Message ----
From  ***@***.***> Date  10/5/2023 22:27 To  ***@***.***> Cc  ***@***.***> ,
 ***@***.***> Subject  Re: [Turoad/CLRNet] error ：nvcc fatal : Unknown option '-generate-dependencies-with-compile' ninja: build stopped: subcommand failed. (Issue #111)  

How to solve this problem?
 I am using the RTX 3090 and installed cuda11.1
