### ISSUE TITLE
Build error "RuntimeError:  Error compiling objects for extension"

### ISSUE THREAD

**Issue by thomiaditya** [Turoad/CLRNet#119]
I got this error when trying to run `python setup.py build develop` script.

```sh
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 100, in <module>
    setup(name='clrnet',
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\dist.py", line 1244, in run_command
    super().run_command(command)
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
    self.run_command(cmd_name)
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\dist.py", line 1244, in run_command
    super().run_command(command)
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\torch\utils\cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\torch\utils\cpp_extension.py", line 681, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\torch\utils\cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Users\thomi\miniconda3\envs\clrnet\lib\site-packages\torch\utils\cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

Im using PyTorch 1.8.0 and CUDA 10.2 as suggested in the main repo. Also because of it run `cl.exe`, I switch the environment to `Visual Studio 2019` powershell environment.

Anybody got a hint?

**Comment by thomiaditya** [comment]
It turns out that I open up the x86 version of MSBuild instead of x64. It works smoothly now.
