### ISSUE TITLE
你好请问我的是什么问题？Hello, what is my problem?

### ISSUE THREAD

**Issue by ZhuFfengJiang** [Turoad/CLRNet#122]
Validate: 100%|███████████████████████████████████████████████████████████████████████████████████ 166/166 [03:40<00:00,  1.33s/it]
Generating prediction output...
2023-08-03 03:43:31,315 - clrnet.utils.culane_metric - INFO - Calculating metric for List: ./data/CULane/list/test_split/test0_normal.txt
Traceback (most recent call last):
  File "main.py", line 75, in <module>
    main()
  File "main.py", line 39, in main
    runner.train()
  File "/home/zhufengjiang/deep/clrnet/clrnet/engine/runner.py", line 98, in train
    self.validate()
  File "/home/zhufengjiang/deep/clrnet/clrnet/engine/runner.py", line 143, in validate
    self.cfg.work_dir)
  File "/home/zhufengjiang/deep/clrnet/clrnet/datasets/culane.py", line 135, in evaluate
    official=True)
  File "/home/zhufengjiang/deep/clrnet/clrnet/utils/culane_metric.py", line 146, in eval_predictions
    predictions = load_culane_data(pred_dir, list_path)
  File "/home/zhufengjiang/deep/clrnet/clrnet/utils/culane_metric.py", line 131, in load_culane_data
    img_data = load_culane_img_data(path)
  File "/home/zhufengjiang/deep/clrnet/clrnet/utils/culane_metric.py", line 110, in load_culane_img_data
    with open(path, 'r') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'work_dirs/clr/r18_culane/20230803_030647_lr_6e-04_b_210/driver_37_30frame/05191714_0507.MP4/04895.lines.txt'

**Comment by zhangzhongyuan1996** [comment]
你找到解决方法了吗？

**Comment by gabaebae123** [comment]
改一下batch_size试试
