### ISSUE TITLE
"list index out of range" while running `setup.py`

### ISSUE THREAD

**Issue by kkasra12** [Turoad/CLRNet#51]
I tried these steps in google colab to run the model, but I got an error while running `setup.py`
```bash
git clone https://github.com/Turoad/clrnet
cd clrnet/
pip install -r requirements.txt
apt install -y ninja-build
python setup.py build develop
```
and the error is:

```
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
running build
running build_py
running egg_info
writing clrnet.egg-info/PKG-INFO
writing dependency_links to clrnet.egg-info/dependency_links.txt
writing requirements to clrnet.egg-info/requires.txt
writing top-level names to clrnet.egg-info/top_level.txt
adding license file 'LICENSE'
writing manifest file 'clrnet.egg-info/SOURCES.txt'
running build_ext
building 'clrnet.ops.nms_impl' extension
Traceback (most recent call last):
  File "setup.py", line 116, in <module>
    zip_safe=False)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/usr/local/lib/python3.7/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/local/lib/python3.7/dist-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 524, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 423, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 1561, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
```

**Comment by xqh5201314** [comment]
do you slove this problem?

**Comment by mengxia1994** [comment]
I meet this when I use torch 1.12 and vision 0.13, maybe it is because of it. Have you guys solved this problem? I used new version torch because of grid_sample onnx support...

**Comment by xqh5201314** [comment]
I use pytorch1.8 slove this error

**Comment by zehranrgi** [comment]
You have to get the right version of pytorch which is indicated in the repo's readme.

@kkasra12
