### ISSUE TITLE
cannot import name 'nms_impl' from 'clrnet.ops'

### ISSUE THREAD

**Issue by newacronym** [Turoad/CLRNet#63]
Traceback (most recent call last):
File "/content/CLRNet/main.py", line 9, in
from clrnet.utils.config import Config
File "/content/CLRNet/clrnet/init.py", line 1, in
from .ops import *
File "/content/CLRNet/clrnet/ops/init.py", line 1, in
from . nms import nms
File "/content/CLRNet/clrnet/ops/nms.py", line 29, in
from . import nms_impl
ImportError: cannot import name 'nms_impl' from 'clrnet.ops' (/content/CLRNet/clrnet/ops/init.py)

**Comment by c1098699678** [comment]
删除build，再次运行setup.py
