### ISSUE TITLE
Tensorrt

### ISSUE THREAD

**Issue by LukeAI** [Turoad/CLRNet#77]
Would you consider releasing the code / plugins for running CLRNet with tensorrt?

**Comment by Turoad** [comment]
We have release the code to branch [deploy](https://github.com/Turoad/CLRNet/tree/deploy). 
You can try it now, and we will merge it to `main` branch soon.

**Comment by izzat1** [comment]
Thanks for sharing the code. I installed as described but got the following error: (no docker). Any idea what I missing
 
python deploy/tensorrt/onnx2trt.py ../CLRNet/configs/clrnet/clr_resnet18_culane.py --model culane_r18.onnx --trt_file culane_r18.trt
[11/16/2022-10:39:30] [TRT] [E] Could not register plugin creator -  ::MMCVModulatedDeformConv2d version 1
Traceback (most recent call last):
  File "deploy/tensorrt/onnx2trt.py", line 206, in <module>
    onnx2tensorrt(args.config, args.model,
  File "deploy/tensorrt/onnx2trt.py", line 104, in onnx2tensorrt
    trt_engine = onnx2trt(
  File "/media/Disk0/izzat/Lane_camera/CLRNet-deploy/deploy/tensorrt/tensorrt_utils.py", line 144, in onnx2trt
    raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
RuntimeError: parse onnx failed:
In node 202 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
